### ISSUE TITLE
Bug with client or server when using Zipkin 2.11 docker image or newer

### ISSUE THREAD

**Issue by AceHack** [openzipkin/zipkin4net#224] opened 2019-01-03 22:58 UTC
The 2.10 docker image works fine, 2..11 or newer breaks nesting and also the service graph.

I'm running the following
2.10 - `docker run --rm -it -p 9411:9411 openzipkin/zipkin:2.10`
2.11 - `docker run --rm -it -p 9411:9411 openzipkin/zipkin:2.11`

2.10 - Working
![2 10](https://user-images.githubusercontent.com/578953/50666042-088a7400-0f81-11e9-83ef-ee838219a24d.jpg)

2.11 - Broken Nesting
![2 11](https://user-images.githubusercontent.com/578953/50666045-0a543780-0f81-11e9-9e41-7c25a124ac2f.jpg)

```
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using zipkin4net;
using zipkin4net.Middleware;
using zipkin4net.Tracers.Zipkin;
using zipkin4net.Transport.Http;

namespace TracingTest
{
    class Program
    {
        static readonly DateTime _startDateTime;
        static readonly long _startTicks;
        static Program()
        {
            _startDateTime = DateTime.UtcNow;
            _startTicks = System.Diagnostics.Stopwatch.GetTimestamp();
        }

        static async Task Main(string[] args)
        {
            using (var services = new ServiceCollection()
                .AddLogging(builder =>
                {
                    builder
                    .AddConsole()
                    .AddDebug();
                })
                .BuildServiceProvider()
            )
            {
                TraceManager.SamplingRate = 1;
                var loggerFactory = services.GetRequiredService<ILoggerFactory>();
                var logger = new TracingLogger(loggerFactory, "Tracing");
                var sender = new HttpZipkinSender("http://localhost:9411", "application/json");
                var serializer = new JSONSpanSerializer();
                var tracer = new ZipkinTracer(sender, serializer);
                TraceManager.RegisterTracer(tracer);
                TraceManager.Start(logger);

                // Timings
                var uiStart = UtcNow;
                var gatewayStart = uiStart.AddMilliseconds(10);
                var gatewayCallAuthStart = gatewayStart.AddMilliseconds(10);
                var gatewayCallProfileStart = gatewayStart.AddMilliseconds(20);
                var authStart = gatewayCallAuthStart.AddMilliseconds(10);
                var authEnd = authStart.AddMilliseconds(500);
                var gatewayCallAuthEnd = authEnd.AddMilliseconds(10);
                var profileStart = gatewayCallProfileStart.AddMilliseconds(10);
                var profileEnd = profileStart.AddMilliseconds(100);
                var gatewayCallProfileEnd = profileEnd.AddMilliseconds(10);
                var gatewayEnd = new DateTime(Math.Max(gatewayCallAuthEnd.Ticks, gatewayCallProfileEnd.Ticks), DateTimeKind.Utc).AddMilliseconds(10);
                var uiEnd = gatewayEnd.AddMilliseconds(10);

                // UI Call Gateway
                var uiTrace = Trace.Create();
                uiTrace.Record(Annotations.ServiceName("client"));
                uiTrace.Record(Annotations.Rpc("get-user"));
                uiTrace.Record(Annotations.ClientSend(), uiStart);
                uiTrace.Record(Annotations.ClientRecv(), uiEnd);

                // Gateway
                var gatewayTrace = uiTrace.Child();
                gatewayTrace.Record(Annotations.ServiceName("api-gateway"));
                gatewayTrace.Record(Annotations.Rpc("get-user"));
                gatewayTrace.Record(Annotations.ServerRecv(), gatewayStart);
                gatewayTrace.Record(Annotations.ServerSend(), gatewayEnd);

                // Gateway Call Auth
                var gatewayCallAuthTrace = gatewayTrace.Child();
                gatewayCallAuthTrace.Record(Annotations.ServiceName("auth-service"));
                gatewayCallAuthTrace.Record(Annotations.Rpc("get-permissions"));
                gatewayCallAuthTrace.Record(Annotations.ClientSend(), gatewayCallAuthStart);
                gatewayCallAuthTrace.Record(Annotations.ClientRecv(), gatewayCallAuthEnd);

                // Gateway Call Profile
                var gatewayCallProfileTrace = gatewayTrace.Child();
                gatewayCallProfileTrace.Record(Annotations.ServiceName("api-gateway"));
                gatewayCallProfileTrace.Record(Annotations.Rpc("get-profile"));
                gatewayCallProfileTrace.Record(Annotations.ClientSend(), gatewayCallProfileStart);
                gatewayCallProfileTrace.Record(Annotations.ClientRecv(), gatewayCallProfileEnd);

                // Auth Service
                var authTrace = gatewayCallAuthTrace.Child();
                authTrace.Record(Annotations.ServiceName("auth-service"));
                authTrace.Record(Annotations.Rpc("get-permissions"));
                authTrace.Record(Annotations.ServerRecv(), authStart);
                authTrace.Record(Annotations.ServerSend(), authEnd);

                // Profile Service
                var profileTrace = gatewayCallProfileTrace.Child();
                profileTrace.Record(Annotations.ServiceName("profile-service"));
                profileTrace.Record(Annotations.Rpc("get-profile"));
                profileTrace.Record(Annotations.ServerRecv(), profileStart);
                profileTrace.Record(Annotations.ServerSend(), profileEnd);


                // Wait for key to close program
                Console.ReadKey(true);
                TraceManager.Stop();
                TraceManager.ClearTracers();
            }
        }

        static DateTime UtcNow => _startDateTime.AddTicks(System.Diagnostics.Stopwatch.GetTimestamp() - _startTicks);
    }
}
```

**Comment by AceHack** [comment] 2019-01-08 15:10
Server guys said this is a bug in the client, it's incorrectly setting the shared flag.  Do you guys have any idea on when a fix might be made?  Thanks.

**Comment by AceHack** [comment] 2019-02-04 18:23
any update?

**Comment by codefromthecrypt** [comment] 2019-02-06 02:49
the related issue raised in zipkin showed a data classification problem. This would be easier to determine if other work such as https://github.com/openzipkin/zipkin4net/pull/196 was complete

In general it is hard to help troubleshooting when a library is not getting maintenance or change merged

**Comment by codefromthecrypt** [comment] 2019-02-06 02:53
in general, examples that aren't in the same main class are more representative. for example, this isn't running multiple services, it is trying to simulate all in the same class. There might be an issue in expectations around the same service name at the reporting layer. It would probably be good to validate that a more realistic example (services are in different processes) is also "broke"

ex https://github.com/openzipkin/zipkin4net/tree/master/Examples/aspnetcore uses multiple processes and so is a more valid thing to troubleshoot

This is best advice I can give for now.

**Comment by AceHack** [comment] 2019-02-06 03:14
@adriancole this is a real use case, we have services that call themselves so they are both client and server.  Also 1 hop works, it's the 2nd hop that stops things from working, so aspnetcore example does not have enough hops to reproduce the problem.

**Comment by codefromthecrypt** [comment] 2019-02-06 03:29
my advice is to make a copy of the aspnet example which introduces another
hop then.

others can feel free to advise as well

**Comment by AceHack** [comment] 2019-02-06 03:37
@adriancole so you are saying it's not a supported scenario that a "host" call itself in a client/server scenario by zipkin?  In our system, a single "host" process can "host" more than one "service".

**Comment by codefromthecrypt** [comment] 2019-02-06 03:54
people host multiple services in the same process however the data created
from your example is not consistent with practice. that doesn't mean your
code is wrong but to identify if the tracer has a problem the example has
to be more realistic.


when hosting multiple services, the local tree from incoming request to
outgoing should have a consistent local service name. if you want to put
multiple services in the same process you should identify each server span
consistently with that service name. so that would not change from incoming
(server span) to outgoing request (client span). the data produced here is
inconsistent as the server span's local service disagrees with its child
span (client)

sorry but this is last rehash I can give on this as many projects need help

**Comment by AceHack** [comment] 2019-02-06 04:06
@adriancole I'm not sure I follow, if you think the code is incorrect, please tell me how to correct the code, .NET seems to be 2nd class for zipkin as there are almost no examples or help on full solutions.  Our services do not use MVC they use grpc so trying to start from aspnetcore example is a non-starter as there is tons of middleware magic that sets up zipkin.  We are basically "Instrumenting a library" and tried to follow this guide https://zipkin.io/pages/instrumenting where it says you guys are happy to help.

One of the deciding factors in choosing zipkin what this sentence from that guide. 
> "We’ll be extremely happy to help you along the way."

**Comment by codefromthecrypt** [comment] 2019-02-06 04:18
I'm trying to help you dont seem willing to make an example that reproduces
the concern in a valid way. it would seem faster and more productive to try

**Comment by AceHack** [comment] 2019-02-06 04:20
@adriancole Like I said I don't understand what you are saying that makes my example invalid.

**Comment by codefromthecrypt** [comment] 2019-02-06 04:37
what is invalid is that you are sending all "traffic" through the same
process and in a single thread and the same tracer instance. this produces
unrealistic data vs if your test used different instances between each node.

that is unless your actual code is a monolith and they all share the same
process. but that isnt what you describe

to make it more realistic you need to least separate the processes using
separate tracers. the reason why the frontend backend example exists is to
help troubleshoot issues like you have here. in all languages we use this
to debug reporting problems by sometimes modifying it. for example I a
couple weeks ago modified one to send concurrent requests to get to the
bottom of the issue and not be distracted by other things.

anyway that is the reason why I ask if you can make the example temporarily
make 2 calls instead of one.

if that isnt something you can do that is your choice just recognize I am
taking time from others trying to help you. you may not like my help but I
earnestly want to help progress this.

**Comment by AceHack** [comment] 2019-03-19 03:27
I ended up just writing my own .NET zipkin client from scratch that uses the v2 API via protobuf.  It also does batches, circuit breaker, and retries.  All things that are missing from the current .NET client.

**Comment by codefromthecrypt** [comment] 2019-03-19 03:50
thanks for the feedback and good luck

**Closed as completed by codefromthecrypt** 2019-03-19 03:50 UTC
